CREATE TABLE NORBERT_IMAGES (
  IMAGE_ID            NUMBER(5) PRIMARY KEY,
  NAME          VARCHAR(50),
  DESCRIPTION   VARCHAR2(500),
  CREATED_DATE  DATE,
  IMAGE_DATA    BLOB
);

CREATE TABLE NORBERT_TAGS(
  ID           NUMBER(5) PRIMARY KEY,
  NAME         VARCHAR(50),
  CREATED_DATE DATE
);

CREATE TABLE NORBERT_CATALOGUES(
  CATALOGUE_ID NUMBER(5) PRIMARY KEY,
  TITLE        VARCHAR(50),
  CREATED_DATE DATE
);

CREATE TABLE NORBERT_BYTEDATA(
  ID          NUMBER(19) PRIMARY KEY,
  DATA        BLOB NOT NULL
);

CREATE TABLE NORBERT_IMG_TAGS(
  IMAGE_ID    NUMBER(19),
  TAG_ID      NUMBER(19)
);

CREATE SEQUENCE NORBERT_IMAGE_ID_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE NORBERT_CATALOGUE_ID_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE NORBERT_TAG_ID_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE NORBERT_BYTEDATA_ID_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE NORBERT_TAG_ID_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1;
