CREATE TABLE NORBERT_IMAGES (
  IMAGE_ID      NUMBER(19)      PRIMARY KEY,
  NAME          VARCHAR(50)     NOT NULL,
  DESCRIPTION   VARCHAR2(200),
  CATALOGUE_ID  NUMBER(19),
  CREATED_DATE  DATE            NOT NULL,
  THUMB_ID      NUMBER(19)      NOT NULL,
  MED_ID        NUMBER(19)      NOT NULL,
  DOWNLOAD_ID   NUMBER(19)      NOT NULL,
  DATATYPE      VARCHAR2(10)
);

CREATE TABLE NORBERT_TAGS(
  TAG_ID        NUMBER(19)       PRIMARY KEY,
  NAME          VARCHAR(50)      UNIQUE NOT NULL,
  CREATED_DATE  DATE             NOT NULL,
  IMAGE_ID      NUMBER(19)
);

CREATE TABLE NORBERT_CATALOGUES(
  CATALOGUE_ID  NUMBER(19)       PRIMARY KEY,
  TITLE         VARCHAR(50)      UNIQUE NOT NULL,
  CREATED_DATE  DATE
);

CREATE TABLE NORBERT_BYTEDATA(
  ID            NUMBER(19)       PRIMARY KEY,
  DATA          BLOB             NOT NULL
);

CREATE TABLE NORBERT_IMG_TAGS(
  IMAGE_ID      NUMBER(19)       NOT NULL,
  TAG_ID        NUMBER(19)       NOT NULL
);

CREATE SEQUENCE NORBERT_CATALOGUE_ID_SEQ
MINVALUE      1
START WITH    1
INCREMENT BY  1;

CREATE SEQUENCE NORBERT_IMAGE_ID_SEQ
MINVALUE      1
START WITH    1
INCREMENT BY  1;

CREATE SEQUENCE NORBERT_TAG_ID_SEQ
MINVALUE      1
START WITH    1
INCREMENT BY  1;

CREATE SEQUENCE NORBERT_BYTEDATA_ID_SEQ
MINVALUE      1
START WITH    1
INCREMENT BY  1;